[package]
name = "ink_stream"
version = "0.2.0"
edition = "2021"
description = "InkStream: publish novels, buy forever, stream to read (pay per second), resell with royalties."
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
writer_wave = { path = "../writer_wave" }
